#!/usr/bin/env python3
"""Regenerate the MoveIt self-collision matrices, one per tool.

Why this is generated and not hand-written: mod101's URDF is parametric. The
rail lengths and the small|big mount swap move link geometry around, so which
pairs "never collide" is a property of the *build*, not of the design. Freezing
one matrix would silently over-disable pairs on a long-armed build (planner
happily drives the forearm through the base) or under-disable on a short one
(everything reports self-collision and nothing plans).

Run after changing any build parameter — the configurator's Save is the usual
trigger:

    python3 tools/gen_collision_matrix.py                  # current defaults
    python3 tools/gen_collision_matrix.py --tool jaws      # just one
    python3 tools/gen_collision_matrix.py --trials 50000   # more thorough

Needs a sourced ROS 2 Jazzy + a built workspace (it shells out to xacro and to
moveit_setup_assistant's collisions_updater against the installed packages).
"""

import argparse
import os
import re
import subprocess
import sys
import pathlib
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / 'src' / 'mod101_moveit_config' / 'config' / 'collisions'
TOOLS = ('jaws', 'parallel', 'pincopen', 'none')

# Build args forwarded to the URDF. The configurator owns them, so read them
# back from the file it writes rather than hardcoding. They used to live in
# mod101.xacro; they moved to mod101_config.xacro so every consumer of the
# mod101_arm macro (including base101) shares one source of truth.
XACRO_MOD101 = ROOT / 'src' / 'mod101_description' / 'urdf' / 'mod101.xacro'
CONFIG_XACRO = ROOT / 'src' / 'mod101_description' / 'urdf' / 'mod101_config.xacro'
ARG_RE = re.compile(
    r'<xacro:arg\s+name="(shoulder_ext_length|elbow_ext_length|'
    r'shoulder_mount|elbow_mount)"\s+default="([^"]+)"')

HEADER = """<?xml version="1.0"?>
<!--
  GENERATED by tools/gen_collision_matrix.py — do not edit by hand.

  tool={tool}  {build}
  {npairs} disabled pairs out of {ntotal} ({ndefault} default/adjacent,
  {nnever} never-colliding over {trials} random samples).

  Regenerate after changing any build parameter; see the script's docstring for
  why this can't be a static file.
-->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:macro name="mod101_collisions_{tool}" params="prefix:=''">
"""

FOOTER = """</xacro:macro>
</robot>
"""


def build_args():
    """The four build params as the configurator last saved them."""
    args = dict(ARG_RE.findall(CONFIG_XACRO.read_text()))
    missing = {'shoulder_ext_length', 'elbow_ext_length',
               'shoulder_mount', 'elbow_mount'} - args.keys()
    if missing:
        sys.exit(f'{CONFIG_XACRO}: missing build args {sorted(missing)}')
    return args


def bootstrap_srdf(tool, prefix=''):
    """A minimal SRDF with the groups but no disable_collisions.

    collisions_updater needs a valid SRDF to start from, and the real one
    includes the file we're about to write — so build a standalone one here
    instead of expanding mod101.srdf.xacro (which would be circular on a fresh
    checkout where the matrices are still empty stubs).
    """
    return f"""<?xml version="1.0"?>
<robot name="mod101">
  <group name="{prefix}arm">
    <chain base_link="{prefix}base_link" tip_link="{prefix}wrist_flange"/>
  </group>
  <virtual_joint name="virtual_joint" type="fixed"
                 parent_frame="world" child_link="world"/>
</robot>
"""


def run(cmd, **kw):
    proc = subprocess.run(cmd, capture_output=True, text=True, **kw)
    if proc.returncode != 0:
        sys.exit(f'! {" ".join(cmd)}\n{proc.stdout}\n{proc.stderr}')
    return proc.stdout


def generate(tool, trials, args):
    print(f'==> {tool}', flush=True)
    mappings = [f'{k}:={v}' for k, v in args.items()] + [f'tool:={tool}']

    with tempfile.TemporaryDirectory() as td:
        td = Path(td)
        urdf, srdf_in, srdf_out = td / 'r.urdf', td / 'in.srdf', td / 'out.srdf'

        urdf_text = run(['xacro', str(XACRO_MOD101), *mappings])
        urdf.write_text(urdf_text)
        srdf_in.write_text(bootstrap_srdf(tool))
        nlinks = len(re.findall(r'<link name=', urdf_text))

        run(['ros2', 'run', 'moveit_setup_assistant', 'collisions_updater',
             '--urdf', str(urdf), '--srdf', str(srdf_in),
             '--output', str(srdf_out),
             '--default', '--always', '--trials', str(trials)])

        pairs = re.findall(r'<disable_collisions[^/]*/>', srdf_out.read_text())

    # Re-emit prefix-parameterised so multi-arm robots can reuse the macro.
    body = []
    counts = {'default': 0, 'never': 0, 'always': 0}
    for p in pairs:
        reason = re.search(r'reason="([^"]*)"', p)
        r = (reason.group(1) if reason else '').lower()
        counts['never' if r == 'never' else
               'always' if r == 'always' else 'default'] += 1
        p = re.sub(r'(link[12]=")', r'\1${prefix}', p)
        body.append('  ' + p)

    ntotal = nlinks * (nlinks - 1) // 2

    header = HEADER.format(
        tool=tool,
        build=' '.join(f'{k}={v}' for k, v in args.items()),
        npairs=len(pairs), ntotal=ntotal or '?',
        ndefault=counts['default'] + counts['always'],
        nnever=counts['never'], trials=trials)

    (OUT_DIR / f'{tool}.srdf.xacro').write_text(
        header + '\n'.join(body) + '\n' + FOOTER)
    print(f'    {len(pairs)} pairs disabled '
          f'({counts["default"] + counts["always"]} adjacent/always, '
          f'{counts["never"]} never)')


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--tool', choices=TOOLS, action='append',
                    help='only this tool (repeatable); default all')
    ap.add_argument('--trials', type=int, default=10000,
                    help='random samples for never-colliding search')
    # Overrides for the four build params. Default is "whatever
    # mod101_config.xacro currently says", i.e. whatever the configurator last
    # saved — pass these only to generate for a config you haven't committed.
    for name in ('shoulder-ext-length', 'elbow-ext-length'):
        ap.add_argument(f'--{name}', help='rail length, m')
    for name in ('shoulder-mount', 'elbow-mount'):
        ap.add_argument(f'--{name}', choices=('small', 'big'))
    ap.add_argument('--out-dir', help='write elsewhere (for comparing configs)')
    opts = ap.parse_args()

    if not os.environ.get('ROS_DISTRO'):
        sys.exit('source /opt/ros/jazzy/setup.bash and the workspace first')

    args = build_args()
    for key in ('shoulder_ext_length', 'elbow_ext_length',
                'shoulder_mount', 'elbow_mount'):
        override = getattr(opts, key, None)
        if override:
            args[key] = override
    print(f'build params: {args}')

    global OUT_DIR
    if opts.out_dir:
        OUT_DIR = pathlib.Path(opts.out_dir)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for tool in (opts.tool or TOOLS):
        generate(tool, opts.trials, args)


if __name__ == '__main__':
    main()
